source "https://rubygems.org"

gem 'eventmachine', "~> 1.0"
gem "em-http-request", "~> 1.0"
gem "nats"
gem "ruby-hmac"
gem "uuidtools"
gem "datamapper", ">= 0.10.2"
gem "dm-sqlite-adapter"
gem "do_sqlite3"
gem "sinatra"
gem "thin"
gem "redis"
gem "rake"
gem "curb"

gem 'vcap_common', :require => ['vcap/common', 'vcap/component'], :git => 'git://github.com/cloudfoundry/vcap-common.git'
gem 'vcap_logging', :require => ['vcap/logging'], :git => 'git://github.com/cloudfoundry/common.git'
# # gem 'vcap_services_base', :git => 'git://github.com/cloudfoundry/vcap-services-base.git'
gem 'vcap_services_base', :git => 'git://github.com/drnic/vcap-services-base.git', branch: 'latest_edge_gems'

group :test do
  gem "rake"
  gem "rspec"
  gem "rcov", "~> 0.9.11"
  gem "simplecov"
  gem "simplecov-rcov"
  gem "ci_reporter"
end
