#!/bin/bash
<%
node = properties.redis_node
%>
JOB_DIR=/var/vcap/jobs/redis_node
PKG_DIR=/var/vcap/packages/redis_node

REDIS26_BIN_DIR=/var/vcap/packages/redis26/bin


SERVICE_NAME="redis"
SOCKET_FILE=<%= node.warden_socket_path || "/tmp/warden.sock" %>
source /var/vcap/packages/redis_node/common/services/utils.sh

case $1 in

  start)
    setup_warden
    start_warden
    ;;

  stop)
    if [ -f /var/vcap/sys/run/warden/warden.pid ]; then
      PIDFILE=/var/vcap/sys/run/warden/warden.pid
    fi
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: warden_ctl {start|stop}"
    ;;

esac
